### ISSUE TITLE
Allow adding build outputs to a resource library

### ISSUE THREAD

**Issue by wirew0rm** [vector-of-bool/cmrc#38]
Right now it seems that cmrc only supports adding files from the sourcetree.
I have an application where I have to add some build outputs to the resource library, but there seems to be a configure time check for the existence of the file. The actual conversion of the file is performed at build time, so I can ensure that the target generating the file is executed before and the file is present.

As a workaround I've added a `file(TOUCH ...)` command before the cmrc calls. This works but looks a bit funny.

Is there a better way to do this right now? Is it a valid usecase?
Possible improvements to cmrc in this regard:
 - remove the check (probably not good for the majority of users)
 - move the check to build-time
 - add a flag to skip the test
 - add a new command variant which accepts a target as a dependency and does not perform the test for build artifacts.

I'd be happy to contribute a PR but I wanted to make sure that this isn't already supported or going into the wrong direction.

My usecase is to compile a webasembly client in a cmake `ExternalProject_add` call and then add the .wasm/.html files as resources to the server component which will serve them next to the api endpoint.

**Comment by vector-of-bool** [comment]
cmrc doesn't have an explicit check itself, but you may be seeing the issue due to the `add_custom_command` that declares a dependency on the input files. If CMake has no way to verify that the file already exists _or_ will be generated by a build-time process, it may be unhappy.

In the case of files generated at build-time via `ExternalProject_Add`, you may want to try the `BYPRODUCTS` or `BUILD_BYPRODUCTS` options (Refer: https://cmake.org/cmake/help/latest/module/ExternalProject.html). If I understand correctly, this will "promise" to CMake that the files in question will be generated as part of the external project's build, and it will know to build the external project before it attempts to compile the resource library.

**Comment by wirew0rm** [comment]
Ah yes, `BUILD_BYPRODUCTS` did the trick :+1: 

Thank you for the solution and the detailed explanation, in hindsight it looks pretty straightforward that somewhere the rules for these files have to be generated.

**Comment by vector-of-bool** [comment]
I tweaked the issue title for more search-ability, and I'll leave this here in case it is useful for anyone who may have a similar issue.

**Comment by wirew0rm** [comment]
In case it is useful for anyone, here is the full sample including compiled wasm binaries into cmrc. First in the main CMakeList the `ExternalProject_Add` call with the `BUILD_BYPRODUCTS` parameter for the generated resources:
https://github.com/fair-acc/opendigitizer/blob/d928c7d8b765936ef7a2f96c68a7f4a26e13fb26/CMakeLists.txt#L16-L31
and then the actual CMRC call in the native part of the project referring to them: 
https://github.com/fair-acc/opendigitizer/blob/d928c7d8b765936ef7a2f96c68a7f4a26e13fb26/src/service/rest/CMakeLists.txt#L15-L19
